CREATE SCHEMA IF NOT EXISTS DB01TEX AUTHORIZATION sa;

CREATE TABLE IF NOT EXISTS DB01TEX.FILMS(
     id         INTEGER  IDENTITY(1,1) NOT NULL PRIMARY KEY
    ,ano        INTEGER  NOT NULL
    ,titulo     VARCHAR(100) NOT NULL
    ,estudio    VARCHAR(100) NOT NULL
    ,produtores VARCHAR(500) NOT NULL
    ,vencedor   CHAR(1) NOT NULL
);

DELETE FROM DB01TEX.FILMS